# Generated by Django 3.0.8 on 2021-02-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210116_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='disc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
