# Generated by Django 3.0.8 on 2021-02-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_order_disc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='disc',
            new_name='note',
        ),
    ]
